language: php

php: "7.1"
node_js: "7"

install: "npm install"
script: "npm run build"

# TODO:
# recursively remove api/storage
# recursively remove api/bootstrap/cache
# copy dist/ to FTP server
#after_success:
#  - "curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://sitename.com/directory/myfile"

#notifications:
#  webhooks:
#    urls:
#      - http://thermoboard.sebastianhaeni.ch/api/migrate
#    on_success: always
