language: php

php: "7.1"
node_js: "7"

install:
  - npm install
  - cd api
  - composer install --optimize-autoloader

before_script:
  - chmod +x scripts/deploy.sh

script:
  - npm run build
  - scripts/deploy.sh
