language: php

php: "7.1"
node_js: "7"

install: "npm install"
script: "npm run build"

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master

notifications:
  webhooks:
    urls:
      - http://thermoboard.sebastianhaeni.ch/api/migrate
    on_success: always
    on_failure: never
